{{- if .Values.backend.enabled }}
{{- if .Values.backend.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thebot.backend.name" . }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "thebot.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "thebot.backend.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
