{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thebot.secretName" . }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "thebot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value }}
  {{- end }}

  # Additional computed secrets
  POSTGRES_PASSWORD: {{ .Values.postgresql.env.POSTGRES_PASSWORD | default "changeme" | quote }}
{{- end }}
