{{- if .Values.rbac.enabled }}
{{- if .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thebot.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "thebot.labels" . | nindent 4 }}
{{- end }}
{{- end }}
